version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: web-scraper-api-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: web-scraper-api-server
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - NUM_WORKERS=4
      - PUPPETEER_HEADLESS=true
      - LOG_LEVEL=info
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./api/logs:/app/logs

volumes:
  redis_data: